name: PHP Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: laravel
          MYSQL_USER: root
          MYSQL_PASSWORD: ''
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set PHP env
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, exif, pcntl

      - name: Install dependencies with composer
        run: composer install --prefer-dist --no-interaction

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run migrations with seed
        run: php artisan migrate --seed

      - name: Run tests
        run: php artisan test
