name: PHP Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set PHP env
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies with composer
        run: composer install

      - name: Run tests
        run: php artisan test
